name: Setanta ADV
favicon: null
layout_spectrum: 0.9487089647445828
typography_spectrum: 0.08949504303745925
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffff80'
    - '#ff0000'
    - '#ff8080'
    - '#808000'
    - '#000000'
  brandStrength: 0.1875
  lightness: 0.15233681164681911
  saturation: 0.7072342329192907
  rhythmicContrast: 0.39185184333473444
purpose: []
