name: Setanta ADV
favicon: null
layout_spectrum: 0.0047
typography_spectrum: 0.80473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#a41e21'
    - '#c38f3a'
    - '#efc977'
    - '#6e5126'
  brandStrength: 0.1875
  lightness: 0.15233681164681911
  saturation: 0.7072342329192907
  rhythmicContrast: 0.39185184333473444
purpose: []
